---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Release.Name }}-service
  name: {{ .Release.Name }}-service
spec:
  selector:
    app: {{ .Release.Name }}-deployment
  ports:
  - name: grafana
    protocol: TCP
    port: 3000
    targetPort: 3000
